FROM node:20-alpine

# Install Angular CLI globally and curl for healthchecks
RUN apk add --no-cache curl \
    && npm install -g @angular/cli@17 --silent

# Create workspace directory
WORKDIR /workspace/pos-frontend

EXPOSE 4200

CMD ["tail", "-f", "/dev/null"]
