# Use official Maven image with Java 17 — no need to download Maven manually
FROM maven:3.9.6-eclipse-temurin-17

# Install utilities
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

ENV MAVEN_CONFIG=/root/.m2

# Create workspace directory
WORKDIR /workspace/pos-backend

CMD ["mvn", "quarkus:dev", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.analytics.disabled=true", "-Dquarkus.log.level=ERROR", "-Dquarkus.log.category.\"io.quarkus\".level=WARN"]
